# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d08323f570fd410c1a13f287a04997c262e0d0f2cf210154640f93b34f99f3d9af21c7409d3478308492d04a30046d9f9262968ed718e03fbfd272d54a093855

test:
  secret_key_base: 1e525a373ebb41f421546bfbeca53bf90c1a8b76142f0168772db5fa551900581d6451dba7c98e65ad105620d7ecde6deecfbe8a42e69344ba8b720888dd11ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
